-- MySQL Script generated by MySQL Workbench
-- Mon Dec 30 16:04:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema brewday
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brewday
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brewday` DEFAULT CHARACTER SET utf8 ;
USE `brewday` ;

-- -----------------------------------------------------
-- Table `brewday`.`Storage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brewday`.`Storage` (
  `idStorage` INT NOT NULL,
  PRIMARY KEY (`idStorage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brewday`.`Equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brewday`.`Equipment` (
  `idEquipment` INT NOT NULL,
  `capacity` DOUBLE NOT NULL,
  PRIMARY KEY (`idEquipment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brewday`.`Recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brewday`.`Recipe` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Storage_idStorage` INT NOT NULL,
  `Equipment_idEquipment` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Recipe_Storage1_idx` (`Storage_idStorage` ASC) VISIBLE,
  INDEX `fk_Recipe_Equipment1_idx` (`Equipment_idEquipment` ASC) VISIBLE,
  CONSTRAINT `fk_Recipe_Storage1`
    FOREIGN KEY (`Storage_idStorage`)
    REFERENCES `brewday`.`Storage` (`idStorage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipe_Equipment1`
    FOREIGN KEY (`Equipment_idEquipment`)
    REFERENCES `brewday`.`Equipment` (`idEquipment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brewday`.`Brew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brewday`.`Brew` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `note` LONGTEXT NULL,
  `startDate` DATE NOT NULL,
  `finishDate` DATE NULL,
  `Recipe_id` INT NOT NULL,
  `Storage_idStorage` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Brew_Recipe_idx` (`Recipe_id` ASC) VISIBLE,
  INDEX `fk_Brew_Storage1_idx` (`Storage_idStorage` ASC) VISIBLE,
  CONSTRAINT `fk_Brew_Recipe`
    FOREIGN KEY (`Recipe_id`)
    REFERENCES `brewday`.`Recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Brew_Storage1`
    FOREIGN KEY (`Storage_idStorage`)
    REFERENCES `brewday`.`Storage` (`idStorage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brewday`.`Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brewday`.`Ingredient` (
  `name` INT NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brewday`.`Recipe_has_Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brewday`.`Recipe_has_Ingredient` (
  `Recipe_id` INT NOT NULL,
  `Ingredient_name` INT NOT NULL,
  `quantity` DOUBLE NULL,
  PRIMARY KEY (`Recipe_id`, `Ingredient_name`),
  INDEX `fk_Recipe_has_Ingredient_Ingredient1_idx` (`Ingredient_name` ASC) VISIBLE,
  INDEX `fk_Recipe_has_Ingredient_Recipe1_idx` (`Recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_Recipe_has_Ingredient_Recipe1`
    FOREIGN KEY (`Recipe_id`)
    REFERENCES `brewday`.`Recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipe_has_Ingredient_Ingredient1`
    FOREIGN KEY (`Ingredient_name`)
    REFERENCES `brewday`.`Ingredient` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brewday`.`Storage_has_Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brewday`.`Storage_has_Ingredient` (
  `Storage_idStorage` INT NOT NULL,
  `Ingredient_name` INT NOT NULL,
  `quantity` DOUBLE NULL,
  PRIMARY KEY (`Storage_idStorage`, `Ingredient_name`),
  INDEX `fk_Storage_has_Ingredient_Ingredient1_idx` (`Ingredient_name` ASC) VISIBLE,
  INDEX `fk_Storage_has_Ingredient_Storage1_idx` (`Storage_idStorage` ASC) VISIBLE,
  CONSTRAINT `fk_Storage_has_Ingredient_Storage1`
    FOREIGN KEY (`Storage_idStorage`)
    REFERENCES `brewday`.`Storage` (`idStorage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Storage_has_Ingredient_Ingredient1`
    FOREIGN KEY (`Ingredient_name`)
    REFERENCES `brewday`.`Ingredient` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
