language: java
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk-ea
addons:
  sonarcloud:
    organization: "unimibsoftengcourse1920"
    token:
      secure: $SONAR_TOKEN
script:
  - mvn sonar:sonar